### ISSUE TITLE
Build/Release GH action needs to be updated for new docker image

### ISSUE THREAD

**Issue by mrd0ll4r** [trudi-group/ipfs-metric-exporter#59]
See https://github.com/trudi-group/ipfs-metric-exporter/actions/runs/4053827582
and https://github.com/trudi-group/ipfs-metric-exporter/blob/master/.github/workflows/Build_release.yaml#L16

**Comment by mg98** [comment]
Sorry, my bad. [My master branch](https://github.com/mg98/ipfs-metric-exporter/blob/master/.github/workflows/Build_release.yaml) got it right, though.

I also feel about the commit trash. If you want we can

```
git checkout master
git reset --hard c43227bc8c4a82aeb6df2d05af7e0dba00924c56
git push -f
```

and I open a new PR with this fix and commits squashed.

**Comment by mrd0ll4r** [comment]
Hmm yes, the commit spam is not optimal, but I should've noticed before merging. I've adopted a workflow in which I never push additional fixup commits, and instead rebase. Anyway, we can't fix it anymore, no force pushing to master, such is life.
