### ISSUE TITLE
Image cannot be pulled

### ISSUE THREAD

**Issue by mg98** [trudi-group/ipfs-metric-exporter#63]
I noticed the package is not properly shown in the repository. Moreover, I cannot pull.

```
# docker pull ghcr.io/trudi-group/kubo-mexport:latest
Error response from daemon: Head "https://ghcr.io/v2/trudi-group/kubo-mexport/manifests/latest": unauthorized
```

I suspect that the image must have the same name as the repository. So either we tag the image `ipfs-metric-exporter` or rename this repo to `kubo-mexport`.

I found [this](https://stackoverflow.com/questions/70395775/not-all-docker-images-are-showing-on-github-container-registry) which suggests the same.

**Comment by mrd0ll4r** [comment]
That was a permission issue, please try again now :)

**Comment by mg98** [comment]
It works!
